COMPONENT=BlinkAppC

CFLAGS += -DDEFINED_TOS_AM_ADDRESS=0

CFLAGS += -I$(TOSDIR)/lib/printf

CFLAGS += -I$(TSCRIBE)/targets/common
CFLAGS += -I$(TSCRIBE)/targets/tinyos/tscribe

CFLAGS += -v

include $(MAKERULES)

