COMPONENT=TrackingDemoAppC

CFLAGS += -I$(TOSDIR)/lib/printf

CFLAGS += -DDEFINED_TOS_AM_ADDRESS=0
CFLAGS += -DCC2420_DEF_CHANNEL=1

CFLAGS += -I$(TSCRIBE)/targets/common
CFLAGS += -I$(TSCRIBE)/targets/tinyos/tscribe

CFLAGS += -v

include $(MAKERULES)

